### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by yyewolf** [Zingabopp/MultiplayerExtensions#130] opened 2021-06-12 21:45 UTC
**Is your feature request related to a problem? Please describe.**
When I play with another person that is new to the game it can be frustrating to play on Normal all the time.

**Describe the solution you'd like**
Possibility to change difficulties per player. 

**Additional context**
Player 1 selects Normal and plays Normal
Player 2 selects Expert+ and plays Expert+

**Comment by Goobwabber** [comment] 2021-06-15 19:26
duplicate of #42

**Closed by Goobwabber** 2021-06-15 19:26 UTC
Labels: duplicate, enhancement
