### ISSUE TITLE
[BUG] Stuck if song doesn't exist on BeatSaver

### ISSUE THREAD

**Issue by harry1453** [Zingabopp/MultiplayerExtensions#82] opened 2021-01-12 23:13 UTC
**Your Platform**

PC, Steam, mod version 0.4.1

**Describe the bug**
When selecting a song that doesn't exist on songcore, no obvious error is produced, the lobby just gets stuck at "loading" until the host cancels.

**To Reproduce**
1. Create / Join lobby
2. Attempt to play a song that isn't on BeatSaver

**Expected behavior**
An error message or something would appear and the level launch would be cancelled, and players would be kicked back to the level selection screen

**Comment by Goobwabber** [comment] 2021-01-22 23:43
Dupe of #54

**Closed by Goobwabber** 2021-01-22 23:43 UTC
