### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sammie0908** [Zingabopp/MultiplayerExtensions#86] opened 2021-01-22 19:13 UTC
**Your Platform**
PC/Oculus store. Using oculus store to play beat saber.

**Describe the bug**
Can not longer play multiplayer. when we click ready and the counter goes down. It gets stuck at the 'Waiting for player' screen. Additionally, the failed screen glitches over the choosing song and difficulty screen

**To Reproduce**

1. Go to 'Online'
2. Click on 'Join server'
3. Scroll down to 'ready'

**Expected behavior**
The counter will go down and the screen will remain loading endlessly

**Log**
 [DEBUG @ 18:54:13 | IPA/LibraryLoader] Resolving library 0Harmony, Version=2.0.2.0, Culture=neutral, PublicKeyToken=null

**Screenshots/Video**

**Additional context**

**Comment by Goobwabber** [comment] 2021-01-22 19:18
dupe of #83 / #69

**Closed by Goobwabber** 2021-01-22 19:18 UTC
