### ISSUE TITLE
Walls

### ISSUE THREAD

**Issue by Squares2020** [Zingabopp/MultiplayerExtensions#25] opened 2020-11-01 20:28 UTC
If there is a wall at the end of a song that wall will stay there after then song ends but of course disappears when you get into the lobby its something little but still none the less a bug.

**Comment by Zingabopp** [comment] 2020-11-01 21:13
Duplicate of #15

**Comment by ItsCharaHere** [comment] 2020-11-01 21:13
This issue is already reported, see https://github.com/Zingabopp/MultiplayerExtensions/issues/15

**Closed** 2020-11-01 21:13 UTC
