### ISSUE TITLE
[BUG] Blackscreen if you join a Lobby

### ISSUE THREAD

**Issue by IDarky** [Zingabopp/MultiplayerExtensions#44] opened 2020-11-12 20:07 UTC
**Describe the bug**
Blackscreen if you try to join a lobby. The hoster do not have a blackscreen

**To Reproduce**

1. Go on Join Lobby
2. You will get an Black screen

**Expected behavior**
Play with friends custom mods

**Log**
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5533021/_latest.log)

**Installed Mods**

![image](https://user-images.githubusercontent.com/42013222/98990286-8c70f800-252a-11eb-9108-e7fb5ab38b3a.png)

Mayby the Beatsaber Update that just came out destroyed the mod?

I do not have the Saber Factory installed

**Comment by IDarky** [comment] 2020-11-12 20:21
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5533101/_latest.log)

here another log after complete reinstall of beatsaber

**Comment by TheiMacNoob** [comment] 2020-11-13 03:21
I'm having the issue as well. Tested with 4 other people!

**Comment by Zingabopp** [comment] 2020-11-13 05:16
Give the latest build a try, I think I fixed it.

**Comment by TheiMacNoob** [comment] 2020-11-13 05:17
I'll try it in a few minutes! If I don't reply after this, it works!

**Comment by TheiMacNoob** [comment] 2020-11-13 16:35
Just an update, the issue is fixed. You can close this topic (I tested it with 2 other players).

**Comment by IDarky** [comment] 2020-11-13 17:57
yeah this issue is fixed

**Closed** 2020-11-13 19:34 UTC
Labels: bug, question

**Comment by JW6677** [comment] 2020-12-31 01:34
Not for me. Just a black screen when I join a game, I can host a game perfectly fine but I can't join a game. My controller vibrates like there should be menu options though. Here is my log file:
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5756199/_latest.log)
