### ISSUE TITLE
[BUG] Crashing trying to download songs

### ISSUE THREAD

**Issue by gamernjs** [Zingabopp/MultiplayerExtensions#67] opened 2020-12-11 19:52 UTC
Not sure if this has been brought up before. Sorry if I'm repeating. 

 Equipment: SteamVR Valve Index

Takes a very long time attempting to download the missing songs. Player ends up at the "waiting for player" screen. The missing 

song doesn't end up downloading and I usually have to restart my game because it freezes. Everything else this mod add works. 

Awesome mod thank you for creating it. Right now my work around is to have everyone download the songs before creating the 

lobby.

**Comment by bentaisenpai** [comment] 2020-12-11 20:14
I'm pretty sure atm that's because of beat saver not the multiplayer mod. Just like how bsr isn't really downloading all the songs atm.

**Comment by gamernjs** [comment] 2020-12-11 20:29
> I'm pretty sure atm that's because of beat saver not the multiplayer mod. Just like how bsr isn't really downloading all the songs atm.

Well in that case. I'll just be patient and wait for stuff to update then. Thank you

**Comment by Zingabopp** [comment] 2021-01-03 19:00
May be fixed by #73 
Give <https://github.com/Zingabopp/MultiplayerExtensions/actions/runs/459600930> a try

**Comment by Zingabopp** [comment] 2021-01-03 22:13
The change has been merged, please close the issue if this resolves your problem.

**Comment by kevklam** [comment] 2021-01-12 06:49
I am still seeing this issue in 0.4.1 :(

**Comment by gamernjs** [comment] 2021-01-12 06:52
I haven't had a chance to try the updated one yet.

**Comment by kevklam** [comment] 2021-01-12 09:27
Blegh. Was some issue on my end it seems like. Possible interference by the discord presence mod and/or versus. Working for me now.

**Comment by Zingabopp** [comment] 2021-01-12 18:39
This is possibly caused by BeatSaberPresence erroring when the game is launched with Discord not running. Let me know if it happens (and provide your log) if you have the problem with BeatSaberPresence installed and Discord running.

**Comment by gamernjs** [comment] 2021-01-15 03:38
@Zingabopp I just tried it and the mod works beautifully! I uninstalled the discord mod. I didn't have issues in the past with it. But I thought I'd go a head and just remove it. Anyway it works great! Thank you for creating this. This is the missing feature in beat saber and you and anyone else whose worked on this has done an amazing job! I'm very happy this mod exists. Thank you :) 🥇

**Closed** 2021-01-15 03:39 UTC
Labels: bug, question
