### ISSUE TITLE
[FEATURE] Allow players in lobby to select their own difficulties

### ISSUE THREAD

**Issue by DemonAura** [Zingabopp/MultiplayerExtensions#101] opened 2021-02-28 22:32 UTC
**Is your feature request related to a problem? Please describe.**

I usually play decently hard E+ maps but my friends aren't able to keep up with my difficulty. I usually have to play on the lower difficulty to accommodate them but it'd be great to be able to have the functionality of the previous unofficial multiplayer mod that let us pick separate difficulties. I don't mind if our scores are unable to compete, just looking to play with my friends and have everyone at the pace they're comfortable with.

**Describe the solution you'd like**

Add functionality for players to select their own difficulty on maps that support more than one difficulty.

**Additional context**
N/A

**Comment by FreezFree** [comment] 2021-03-01 10:41
Same "problem" here.
I support the request!

**Comment by Goobwabber** [comment] 2021-03-01 21:31
dupe of #42

**Closed by Goobwabber** 2021-03-01 21:31 UTC
Labels: duplicate
